### PR TITLE
[OTAPIv2] Update to 1.4.3.3

### PR DESCRIPTION
**Pull request by 0x3fcf1bbd**
Could build and output a binary with the normal hooks, not sure if it works correctly with TSAPI.
You should be able to edit this if it in fact doesn't work.
Hopefully didn't forget anything, but if a hooked method's signature changed then it was probably not edited here.

### CODE REVIEW

**Comment by SignatureBeef** [comment]
Changes look fine - did you confirm it works via the [Test projects](https://github.com/SignatureBeef/Open-Terraria-API/tree/master/OTAPI.Tests/OTAPI.Server.Tests) ?

**Comment by Patrikkk** [comment]
Changes are incomplete. Not all modifications can be built. 
There has been a change to Terraria.NPC.NewNPC method, an additional parameter - IEntitySource -  has been added at the first position. This has not been addressed in this PR.

**Comment by punchready** [comment]
wat?
`NPC.NewNPC`, `Projectile.NewProjectile`, and `Item.NewItem` now all have an `IEntitySource` as the first parameter, they need to be updated in the patches and in all references... the diff for 1.4.3.3 is huge just because of that
gonna be a bit of work updating every single plugin's `NewNPC` usage again

**Comment by hakusaro** [comment]
> Possibly the "TerrariaServer, Version=1.4.3.2, Culture=neutral, PublicKeyToken=null" string or just 1.4.3.2 could be put into a constant somewhere globally to make it easier to update for new versions?

the end goal is to be on otapi3 in the next couple of months so that we don’t have to do this, but feel free to send a PR

**Comment by SignatureBeef** [comment]
> wat? `NPC.NewNPC`, `Projectile.NewProjectile`, and `Item.NewItem` now all have an `IEntitySource` as the first parameter, they need to be updated in the patches and in all references... the diff for 1.4.3.3 is huge just because of that gonna be a bit of work updating every single plugin's `NewNPC` usage again and also 1.4.3.4 got released half an hour ago with no server related changes (besides the version ofc) Possibly the `"TerrariaServer, Version=1.4.3.2, Culture=neutral, PublicKeyToken=null"` string or just `1.4.3.2` could be put into a constant somewhere globally to make it easier to update for new versions?

doesnt TSAPI use eventargs - so the addition of new properties shouldnt be that difficult ?

**Comment by SignatureBeef** [comment]
closing off as https://github.com/SignatureBeef/Open-Terraria-API/pull/60 has the remaining fixed. thanks for the effort, will still include in the notes.

**Pull request closed without merging**
